// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igsumzbcprhcccbnkspw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlnc3VtemJjcHJoY2NjYm5rc3B3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMDMzODksImV4cCI6MjA3MTg3OTM4OX0.2-vT-D2Sma9P4BwHbAIyJQETqi1JSkZVWEwkgRQKGPw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});